#!/bin/sh

regex='@company\.com$'

email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then 
      echo Your email  $email saticlssfies out policy.
      exit 0
else
     echo  Your email $email dosent satisfies policy. 
     exit 1  
fi        